name: commit

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0 12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Get the date
        run: date > time.txt

      - name: Setup git config
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Commit
        run: |
          git add time.txt
          git commit -m "new date commit"
          git push origin master
